const countryData = [
  { name: "Afghanistan", code: "AF", currencyCode: "AFN" },
  { name: "Albania", code: "AL", currencyCode: "ALL" },
  { name: "Algeria", code: "DZ", currencyCode: "DZD" },
  { name: "Andorra", code: "AD", currencyCode: "EUR" },
  { name: "Angola", code: "AO", currencyCode: "AOA" },
  { name: "Antigua and Barbuda", code: "AG", currencyCode: "XCD" },
  { name: "Argentina", code: "AR", currencyCode: "ARS" },
  { name: "Armenia", code: "AM", currencyCode: "AMD" },
  { name: "Australia", code: "AU", currencyCode: "AUD" },
  { name: "Austria", code: "AT", currencyCode: "EUR" },
  { name: "Azerbaijan", code: "AZ", currencyCode: "AZN" },
  { name: "Bahamas", code: "BS", currencyCode: "BSD" },
  { name: "Bahrain", code: "BH", currencyCode: "BHD" },
  { name: "Bangladesh", code: "BD", currencyCode: "BDT" },
  { name: "Barbados", code: "BB", currencyCode: "BBD" },
  { name: "Belarus", code: "BY", currencyCode: "BYN" },
  { name: "Belgium", code: "BE", currencyCode: "EUR" },
  { name: "Belize", code: "BZ", currencyCode: "BZD" },
  { name: "Benin", code: "BJ", currencyCode: "XOF" },
  { name: "Bhutan", code: "BT", currencyCode: "BTN" },
  { name: "Bolivia", code: "BO", currencyCode: "BOB" },
  { name: "Bosnia and Herzegovina", code: "BA", currencyCode: "BAM" },
  { name: "Botswana", code: "BW", currencyCode: "BWP" },
  { name: "Brazil", code: "BR", currencyCode: "BRL" },
  { name: "Brunei", code: "BN", currencyCode: "BND" },
  { name: "Bulgaria", code: "BG", currencyCode: "BGN" },
  { name: "Burkina Faso", code: "BF", currencyCode: "XOF" },
  { name: "Burundi", code: "BI", currencyCode: "BIF" },
  { name: "Cambodia", code: "KH", currencyCode: "KHR" },
  { name: "Cameroon", code: "CM", currencyCode: "XAF" },
  { name: "Canada", code: "CA", currencyCode: "CAD" },
  { name: "Cape Verde", code: "CV", currencyCode: "CVE" },
  { name: "Central African Republic", code: "CF", currencyCode: "XAF" },
  { name: "Chad", code: "TD", currencyCode: "XAF" },
  { name: "Chile", code: "CL", currencyCode: "CLP" },
  { name: "China", code: "CN", currencyCode: "CNY" },
  { name: "Colombia", code: "CO", currencyCode: "COP" },
  { name: "Comoros", code: "KM", currencyCode: "KMF" },
  { name: "Congo", code: "CG", currencyCode: "XAF" },
  { name: "Costa Rica", code: "CR", currencyCode: "CRC" },
  { name: "Croatia", code: "HR", currencyCode: "EUR" },
  { name: "Cuba", code: "CU", currencyCode: "CUP" },
  { name: "Cyprus", code: "CY", currencyCode: "EUR" },
  { name: "Czech Republic", code: "CZ", currencyCode: "CZK" },
  { name: "Denmark", code: "DK", currencyCode: "DKK" },
  { name: "Djibouti", code: "DJ", currencyCode: "DJF" },
  { name: "Dominica", code: "DM", currencyCode: "XCD" },
  { name: "Dominican Republic", code: "DO", currencyCode: "DOP" },
  { name: "Ecuador", code: "EC", currencyCode: "USD" },
  { name: "Egypt", code: "EG", currencyCode: "EGP" },
  { name: "El Salvador", code: "SV", currencyCode: "USD" },
  { name: "Estonia", code: "EE", currencyCode: "EUR" },
  { name: "Ethiopia", code: "ET", currencyCode: "ETB" },
  { name: "Fiji", code: "FJ", currencyCode: "FJD" },
  { name: "Finland", code: "FI", currencyCode: "EUR" },
  { name: "France", code: "FR", currencyCode: "EUR" },
  { name: "Gabon", code: "GA", currencyCode: "XAF" },
  { name: "Gambia", code: "GM", currencyCode: "GMD" },
  { name: "Georgia", code: "GE", currencyCode: "GEL" },
  { name: "Germany", code: "DE", currencyCode: "EUR" },
  { name: "Ghana", code: "GH", currencyCode: "GHS" },
  { name: "Greece", code: "GR", currencyCode: "EUR" },
  { name: "Guatemala", code: "GT", currencyCode: "GTQ" },
  { name: "Guinea", code: "GN", currencyCode: "GNF" },
  { name: "Guyana", code: "GY", currencyCode: "GYD" },
  { name: "Haiti", code: "HT", currencyCode: "HTG" },
  { name: "Honduras", code: "HN", currencyCode: "HNL" },
  { name: "Hungary", code: "HU", currencyCode: "HUF" },
  { name: "Iceland", code: "IS", currencyCode: "ISK" },
  { name: "India", code: "IN", currencyCode: "INR" },
  { name: "Indonesia", code: "ID", currencyCode: "IDR" },
  { name: "Iran", code: "IR", currencyCode: "IRR" },
  { name: "Iraq", code: "IQ", currencyCode: "IQD" },
  { name: "Ireland", code: "IE", currencyCode: "EUR" },
  { name: "Israel", code: "IL", currencyCode: "ILS" },
  { name: "Italy", code: "IT", currencyCode: "EUR" },
  { name: "Jamaica", code: "JM", currencyCode: "JMD" },
  { name: "Japan", code: "JP", currencyCode: "JPY" },
  { name: "Jordan", code: "JO", currencyCode: "JOD" },
  { name: "Kazakhstan", code: "KZ", currencyCode: "KZT" },
  { name: "Kenya", code: "KE", currencyCode: "KES" },
  { name: "Kuwait", code: "KW", currencyCode: "KWD" },
  { name: "Kyrgyzstan", code: "KG", currencyCode: "KGS" },
  { name: "Laos", code: "LA", currencyCode: "LAK" },
  { name: "Latvia", code: "LV", currencyCode: "EUR" },
  { name: "Lebanon", code: "LB", currencyCode: "LBP" },
  { name: "Lesotho", code: "LS", currencyCode: "LSL" },
  { name: "Liberia", code: "LR", currencyCode: "LRD" },
  { name: "Libya", code: "LY", currencyCode: "LYD" },
  { name: "Lithuania", code: "LT", currencyCode: "EUR" },
  { name: "Luxembourg", code: "LU", currencyCode: "EUR" },
  { name: "Madagascar", code: "MG", currencyCode: "MGA" },
  { name: "Malawi", code: "MW", currencyCode: "MWK" },
  { name: "Malaysia", code: "MY", currencyCode: "MYR" },
  { name: "Maldives", code: "MV", currencyCode: "MVR" },
  { name: "Mali", code: "ML", currencyCode: "XOF" },
  { name: "Malta", code: "MT", currencyCode: "EUR" },
  { name: "Mauritania", code: "MR", currencyCode: "MRU" },
  { name: "Mauritius", code: "MU", currencyCode: "MUR" },
  { name: "Mexico", code: "MX", currencyCode: "MXN" },
  { name: "Moldova", code: "MD", currencyCode: "MDL" },
  { name: "Monaco", code: "MC", currencyCode: "EUR" },
  { name: "Mongolia", code: "MN", currencyCode: "MNT" },
  { name: "Montenegro", code: "ME", currencyCode: "EUR" },
  { name: "Morocco", code: "MA", currencyCode: "MAD" },
  { name: "Mozambique", code: "MZ", currencyCode: "MZN" },
  { name: "Myanmar", code: "MM", currencyCode: "MMK" },
  { name: "Namibia", code: "NA", currencyCode: "NAD" },
  { name: "Nepal", code: "NP", currencyCode: "NPR" },
  { name: "Netherlands", code: "NL", currencyCode: "EUR" },
  { name: "New Zealand", code: "NZ", currencyCode: "NZD" },
  { name: "Nicaragua", code: "NI", currencyCode: "NIO" },
  { name: "Niger", code: "NE", currencyCode: "XOF" },
  { name: "Nigeria", code: "NG", currencyCode: "NGN" },
  { name: "North Korea", code: "KP", currencyCode: "KPW" },
  { name: "North Macedonia", code: "MK", currencyCode: "MKD" },
  { name: "Norway", code: "NO", currencyCode: "NOK" },
  { name: "Oman", code: "OM", currencyCode: "OMR" },
  { name: "Pakistan", code: "PK", currencyCode: "PKR" },
  { name: "Panama", code: "PA", currencyCode: "PAB" },
  { name: "Papua New Guinea", code: "PG", currencyCode: "PGK" },
  { name: "Paraguay", code: "PY", currencyCode: "PYG" },
  { name: "Peru", code: "PE", currencyCode: "PEN" },
  { name: "Philippines", code: "PH", currencyCode: "PHP" },
  { name: "Poland", code: "PL", currencyCode: "PLN" },
  { name: "Portugal", code: "PT", currencyCode: "EUR" },
  { name: "Qatar", code: "QA", currencyCode: "QAR" },
  { name: "Romania", code: "RO", currencyCode: "RON" },
  { name: "Russia", code: "RU", currencyCode: "RUB" },
  { name: "Rwanda", code: "RW", currencyCode: "RWF" },
  { name: "Saudi Arabia", code: "SA", currencyCode: "SAR" },
  { name: "Senegal", code: "SN", currencyCode: "XOF" },
  { name: "Serbia", code: "RS", currencyCode: "RSD" },
  { name: "Singapore", code: "SG", currencyCode: "SGD" },
  { name: "Slovakia", code: "SK", currencyCode: "EUR" },
  { name: "Slovenia", code: "SI", currencyCode: "EUR" },
  { name: "Somalia", code: "SO", currencyCode: "SOS" },
  { name: "South Africa", code: "ZA", currencyCode: "ZAR" },
  { name: "South Korea", code: "KR", currencyCode: "KRW" },
  { name: "Spain", code: "ES", currencyCode: "EUR" },
  { name: "Sri Lanka", code: "LK", currencyCode: "LKR" },
  { name: "Sudan", code: "SD", currencyCode: "SDG" },
  { name: "Sweden", code: "SE", currencyCode: "SEK" },
  { name: "Switzerland", code: "CH", currencyCode: "CHF" },
  { name: "Syria", code: "SY", currencyCode: "SYP" },
  { name: "Taiwan", code: "TW", currencyCode: "TWD" },
  { name: "Tajikistan", code: "TJ", currencyCode: "TJS" },
  { name: "Tanzania", code: "TZ", currencyCode: "TZS" },
  { name: "Thailand", code: "TH", currencyCode: "THB" },
  { name: "Tunisia", code: "TN", currencyCode: "TND" },
  { name: "Turkey", code: "TR", currencyCode: "TRY" },
  { name: "Turkmenistan", code: "TM", currencyCode: "TMT" },
  { name: "Uganda", code: "UG", currencyCode: "UGX" },
  { name: "Ukraine", code: "UA", currencyCode: "UAH" },
  { name: "United Arab Emirates", code: "AE", currencyCode: "AED" },
  { name: "United Kingdom", code: "GB", currencyCode: "GBP" },
  { name: "United States", code: "US", currencyCode: "USD" },
  { name: "Uruguay", code: "UY", currencyCode: "UYU" },
  { name: "Uzbekistan", code: "UZ", currencyCode: "UZS" },
  { name: "Venezuela", code: "VE", currencyCode: "VES" },
  { name: "Vietnam", code: "VN", currencyCode: "VND" },
  { name: "Yemen", code: "YE", currencyCode: "YER" },
  { name: "Zambia", code: "ZM", currencyCode: "ZMW" },
  { name: "Zimbabwe", code: "ZW", currencyCode: "ZWL" },
];

const country11List = document.getElementById("country1List");
const country21List = document.getElementById("country2List");
const country1Img = document.getElementById("country1Img");
const country2Img = document.getElementById("country2Img");
const amount = document.getElementById("amountInput");

country11List.addEventListener('change',(e)=>
{

    console.log(e.target.value);
    country1Img.src = `https://flagsapi.com/${e.target.value}/flat/64.png`;
});

country21List.addEventListener("change", (e) => {

    country2Img.src = `https://flagsapi.com/${e.target.value}/flat/64.png`;
    amount.style.display ="block";
    
});
function addCountryList() {
  countryData.forEach((country) => {
    const option1 = document.createElement("option");
    const option2 = document.createElement("option");
    
    option1.value = country.code;
    option2.value = country.code;
    option1.innerText = `(${country.code}) ${country.name}`;
    option2.innerText = `(${country.code}) ${country.name}`;
    country11List.appendChild(option1);
    country21List.appendChild(option2);
  });
}

addCountryList();

